#
# $Id$
#
#
OBJ=veloc_module.o veloc_wrapper.o sp_init.o sp_main.o 
LIB_INCLUDES=-I${HOME}/veloc-recup/veloc/include
LIBRARY=libspace.a

HEADER=

USES_BLAS=

include ../config/makefile.h

include ../config/makelib.h
